// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShorteningApi.DAL;

#nullable disable

namespace UrlShorteningApi.Migrations
{
    [DbContext(typeof(SQLDBContext))]
    partial class SQLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("UrlShorteningApi.Models.PreviousDayAnalyticsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("dateOnly")
                        .HasColumnType("TEXT");

                    b.Property<string>("longUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("_analyticsModel");
                });

            modelBuilder.Entity("UrlShorteningApi.Models.ShortUrlMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("longUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("shortUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("_shortUrlMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
